### ISSUE TITLE
Todo App fetch 사용 및 데이터 뿌리기

### ISSUE THREAD

**Issue by RyuJiChang** [RyuJiChang/settingTest#4]
### 만들고자 하는 기능이 무엇인가요?
ex) Todo 서버와 소통 및 데이터 뿌려주기

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. [x] fetch를 이용해 서버에서 값 받아오기
2. [ ] fetch 받아온 데이터를 알맞게 배치하기
3. [ ] fetch를 통해 Update, delete, Create 만들기

### 예상 작업 시간
ex) 4h
